
pseudo_dict = {
    "H" : "H.pbe-rrkjus_psl.0.1.UPF",
    "Li" : "Li.pbe-s-rrkjus_psl.0.2.1.UPF",
    "Be" : "Be.pbe-n-rrkjus_psl.0.2.UPF",
    "B" : "B.pbe-n-rrkjus_psl.0.1.UPF",
    "C" : "C.pbe-n-rrkjus_psl.0.1.UPF",
    "N" : "N.pbe-n-rrkjus_psl.0.1.UPF",
    "O" : "O.pbe-n-rrkjus_psl.0.1.UPF",
    "F" : "F.pbe-n-rrkjus_psl.0.1.UPF",
    "Ne" : "Ne.pbe-n-rrkjus_psl.0.3.0.UPF",
    "Na" : "Na.pbe-spn-rrkjus_psl.0.2.UPF",
    "Mg" : "Mg.pbe-n-rrkjus_psl.0.3.0.UPF",
    "Al" : "Al.pbe-n-rrkjus_psl.0.1.UPF",
    "Si" : "Si.pbe-n-rrkjus_psl.0.1.UPF",
    "P" : "P.pbe-n-rrkjus_psl.0.1.UPF",
    "S" : "S.pbe-n-rrkjus_psl.0.1.UPF",
    "Cl" : "Cl.pbe-n-rrkjus_psl.0.3.0.UPF",
    "Ar" : "Ar.pbe-n-rrkjus_psl.0.3.0.UPF",
    "K" : "K.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Ca" : "Ca.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Sc" : "Sc.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Ti": "Ti.pbe-spn-rrkjus_psl.0.3.1.UPF",
    "V": "V.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Cr": "Cr.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Mn": "Mn.pbe-spn-rrkjus_psl.0.3.1.UPF",
    "Fe": "Fe.pbe-n-rrkjus_psl.0.2.4.UPF",
    "Co": "Co.pbe-spn-rrkjus_psl.0.3.1.UPF",
    "Ni": "Ni.pbe-n-rrkjus_psl.0.1.UPF",
    "Cu": "Cu.pbe-dn-rrkjus_psl.0.2.UPF",
    "Zn": "Zn.pbe-dn-rrkjus_psl.0.2.2.UPF",
    "Ga": "Ga.pbe-dn-rrkjus_psl.0.2.UPF",
    "Ge": "Ge.pbe-dn-rrkjus_psl.0.3.1.UPF",
    "As": "As.pbe-n-rrkjus_psl.0.2.UPF",
    "Se": "Se.pbe-n-rrkjus_psl.0.2.UPF",
    "Br": "Br.pbe-n-rrkjus_psl.0.2.UPF",
    "Kr" : "Kr.pbe-n-rrkjus_psl.0.2.3.UPF",
    "Rb": "Rb.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Sr": "Sr.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Y": "Y.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Zr": "Zr.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Nb": "Nb.pbe-spn-rrkjus_psl.0.3.0.UPF",
    "Mo": "Mo.pbe-spn-rrkjus_psl.0.3.0.UPF",
    "Tc": "Tc.pbe-spn-rrkjus_psl.0.3.0.UPF",
    "Ru": "Ru.pbe-spn-rrkjus_psl.0.3.0.UPF",
    "Rh": "Rh.pbe-spn-rrkjus_psl.0.3.0.UPF",
    "Pd": "Pd.pbe-n-rrkjus_psl.0.3.0.UPF",
    "Ag": "Ag.pbe-dn-rrkjus_psl.0.1.UPF",
    "Cd": "Cd.pbe-dn-rrkjus_psl.0.3.1.UPF",
    "In": "In.pbe-dn-rrkjus_psl.0.2.2.UPF",
    "Sn": "Sn.pbe-dn-rrkjus_psl.0.2.UPF",
    "Sb": "Sb.pbe-dn-rrkjus_psl.0.3.1.UPF",
    "Te": "Te.pbe-n-rrkjus_psl.0.3.1.UPF",
    "I": "I.pbe-n-rrkjus_psl.0.2.UPF",
    "Xe": "Xe.pbe-n-rrkjus_psl.0.3.1.UPF",
    "Cs": "Cs.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Ba": "Ba.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Hf": "Hf.pbe-spn-rrkjus_psl.0.2.UPF",
    "Ta": "Ta.pbe-spn-rrkjus_psl.0.2.UPF",
    "W": "W.pbe-spn-rrkjus_psl.0.2.3.UPF",
    "Re": "Re.pbe-spn-rrkjus_psl.0.3.1.UPF",
    "Os": "Os.pbe-n-rrkjus_psl.0.2.3.UPF",
    "Ir": "Ir.pbe-n-rrkjus_psl.0.2.3.UPF",
    "Pt": "Pt.pbe-n-rrkjus_psl.0.1.UPF",
    "Au": "Au.pbe-dn-rrkjus_psl.0.3.0.UPF",
    "Hg": "Hg.pbe-dn-rrkjus_psl.0.2.2.UPF",
    "Tl": "Tl.pbe-dn-rrkjus_psl.0.2.3.UPF",
    "Pb": "Pb.pbe-dn-rrkjus_psl.0.2.2.UPF",
    "Bi": "Bi.pbe-dn-rrkjus_psl.0.2.2.UPF",
    "Po": "Po.pbe-dn-rrkjus_psl.0.3.1.UPF",
    "At": "At.pbe-dn-rrkjus_psl.0.3.1.UPF",
    "Rn": "Rn.pbe-dn-rrkjus_psl.0.3.1.UPF"
    }