wanorb_dict = {
    "N": ["px", "py", "pz"],
    "Ce": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Dy": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Er": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Eu": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Gd": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ho": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "La": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Lu": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Nd": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Pm": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Pr": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Sm": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Tb": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Tm": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Yb": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Bi": ["px", "py", "pz"],
    "Ca": [],
    "Co": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Cs": [],
    "Cu": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ir": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Os": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Re": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Se": ["px", "py", "pz"],
    "Sn": ["px", "py", "pz"],
    "Sr": [],
    "Ta": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Te": ["px", "py", "pz"],
    "Tl": ["px", "py", "pz"],
    "W": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Y": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Zn": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Zr": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "B": ["px", "py", "pz"],
    "Be": [],
    "Br": ["px", "py", "pz"],
    "Cl": ["px", "py", "pz"],
    "Cr": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "F": ["px", "py", "pz"],
    "Ge": ["px", "py", "pz"],
    "Li": [],
    "Mn": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Na": [],
    "Ni": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Pt": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "S": ["px", "py", "pz"],
    "Sb": ["px", "py", "pz"],
    "Ti": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "V": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Hf": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ag": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ar": ["px", "py", "pz"],
    "Au": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "He": [],
    "Hg": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Kr": [],
    "Mo": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ne": ["px", "py", "pz"],
    "Pd": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Rb": [],
    "Rh": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ru": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Sc": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Tc": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Xe": [],
    "Al": ["px", "py", "pz"],
    "As": ["px", "py", "pz"],
    "Ba": [],
    "C": ["px", "py", "pz"],
    "Cd": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Fe": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "Ga": ["px", "py", "pz"],
    "H": ["s"],
    "I": ["px", "py", "pz"],
    "In": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "K": [],
    "Mg": [],
    "Nb": ["dxy", "dyz", "dzx", "dx2", "dz2"],
    "O": ["px", "py", "pz"],
    "P": ["px", "py", "pz"],
    "Pb": ["px", "py", "pz"],
    "Po": ["px", "py", "pz"],
    "Rn": ["px", "py", "pz"],
    "Si": ["px", "py", "pz"],
}
